/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

/**
 *
 * @author Juanfer
 */
public class ConsultasNegocio extends javax.swing.JFrame {

    /**
     * Creates new form ConsultasNegocio
     */
    
    int x,y;
    
    public ConsultasNegocio() {
        
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Consultas Negocio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        c_boton_consultarfecha = new javax.swing.JButton();
        c_boton_consultarmes = new javax.swing.JButton();
        c_combo_dia = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        c_combo_mes = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        c_combo_ano = new javax.swing.JComboBox<>();
        c_boton_consultarano = new javax.swing.JButton();
        c_boton_mostrarproductos = new javax.swing.JButton();
        c_boton_salir = new javax.swing.JButton();
        c_boton_mostrarususarios = new javax.swing.JButton();
        c_boton_mostrarclientes = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        c_text_cedulapedido = new javax.swing.JTextField();
        c_boton_consultarpedido = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        c_text_cedula = new javax.swing.JTextField();
        c_boton_consultarcedula = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        c_botonlimpiar = new javax.swing.JButton();
        c_boton_imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cn_tablaconsultas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel10MouseDragged(evt);
            }
        });
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel10MousePressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 153));
        jLabel27.setText("Area de Consultas:");

        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel40.setText("Consultas por fecha:");

        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel41.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel41.setText("Dia:");

        c_boton_consultarfecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_boton_consultarfecha.setText("Consultar Fecha");
        c_boton_consultarfecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_boton_consultarfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_boton_consultarfechaActionPerformed(evt);
            }
        });

        c_boton_consultarmes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_boton_consultarmes.setText("Consultar Mes");
        c_boton_consultarmes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_boton_consultarmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_boton_consultarmesActionPerformed(evt);
            }
        });

        c_combo_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        c_combo_dia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel42.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel42.setText("Mes:");

        c_combo_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        c_combo_mes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel43.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel43.setText("Año:");

        c_combo_ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2022" }));
        c_combo_ano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        c_boton_consultarano.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_boton_consultarano.setText("Consultar Año");
        c_boton_consultarano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_boton_consultarano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_boton_consultaranoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel41))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(c_combo_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel42))
                    .addComponent(c_combo_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c_combo_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(c_boton_consultarfecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_boton_consultarmes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(c_boton_consultarano)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_combo_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_combo_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(c_boton_consultarfecha)
                                .addComponent(c_boton_consultarmes)
                                .addComponent(c_boton_consultarano)))
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel41)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c_combo_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        c_boton_mostrarproductos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_boton_mostrarproductos.setText("Mostrar Productos");
        c_boton_mostrarproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_boton_mostrarproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_boton_mostrarproductosActionPerformed(evt);
            }
        });

        c_boton_salir.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        c_boton_salir.setText("Salir");
        c_boton_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        c_boton_mostrarususarios.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_boton_mostrarususarios.setText("Mostrar Usuarios");
        c_boton_mostrarususarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_boton_mostrarususarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_boton_mostrarususariosActionPerformed(evt);
            }
        });

        c_boton_mostrarclientes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_boton_mostrarclientes.setText("Mostrar Clientes");
        c_boton_mostrarclientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_boton_mostrarclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_boton_mostrarclientesActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel47.setText("Consultas por Pedido:");

        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel48.setText("Numero Pedido:");

        c_boton_consultarpedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_boton_consultarpedido.setText("Consultar Pedido");
        c_boton_consultarpedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_boton_consultarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_boton_consultarpedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(c_text_cedulapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(c_boton_consultarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(c_text_cedulapedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_boton_consultarpedido))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel45.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel45.setText("Cedula Cliente:");

        c_boton_consultarcedula.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_boton_consultarcedula.setText("Consultar Cedula");
        c_boton_consultarcedula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_boton_consultarcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_boton_consultarcedulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(c_text_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(c_boton_consultarcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(c_text_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_boton_consultarcedula))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel44.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel44.setText("Consultas por Cliente:");

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/Consulta.png"))); // NOI18N

        c_botonlimpiar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_botonlimpiar.setText("Limpiar");
        c_botonlimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_botonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_botonlimpiarActionPerformed(evt);
            }
        });

        c_boton_imprimir.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c_boton_imprimir.setText("Imprimir");
        c_boton_imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_boton_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_boton_imprimirActionPerformed(evt);
            }
        });

        cn_tablaconsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Cod.", "Descripcion", "Precio Unit.", "Importe"
            }
        ));
        cn_tablaconsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(cn_tablaconsultas);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel40))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel60))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel44))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel47))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(c_botonlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(c_boton_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(c_boton_mostrarproductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(c_boton_mostrarususarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(c_boton_mostrarclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(c_boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel27)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel40))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel60)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_botonlimpiar)
                    .addComponent(c_boton_imprimir))
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(c_boton_mostrarclientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_boton_mostrarususarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_boton_mostrarproductos)
                        .addGap(58, 58, 58)
                        .addComponent(c_boton_salir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_boton_consultarfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_boton_consultarfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_boton_consultarfechaActionPerformed

    private void c_boton_consultarmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_boton_consultarmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_boton_consultarmesActionPerformed

    private void c_boton_consultaranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_boton_consultaranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_boton_consultaranoActionPerformed

    private void c_boton_mostrarproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_boton_mostrarproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_boton_mostrarproductosActionPerformed

    private void c_boton_mostrarususariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_boton_mostrarususariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_boton_mostrarususariosActionPerformed

    private void c_boton_mostrarclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_boton_mostrarclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_boton_mostrarclientesActionPerformed

    private void c_boton_consultarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_boton_consultarpedidoActionPerformed
        
    }//GEN-LAST:event_c_boton_consultarpedidoActionPerformed

    private void c_boton_consultarcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_boton_consultarcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_boton_consultarcedulaActionPerformed

    private void c_botonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_botonlimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_botonlimpiarActionPerformed

    private void c_boton_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_boton_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_boton_imprimirActionPerformed

    private void jPanel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MousePressed
         x=evt.getX();
        y=evt.getY();
        
    }//GEN-LAST:event_jPanel10MousePressed

    private void jPanel10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseDragged
      this.setLocation(this.getLocation().x+evt.getX()-x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_jPanel10MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultasNegocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c_boton_consultarano;
    private javax.swing.JButton c_boton_consultarcedula;
    private javax.swing.JButton c_boton_consultarfecha;
    private javax.swing.JButton c_boton_consultarmes;
    private javax.swing.JButton c_boton_consultarpedido;
    private javax.swing.JButton c_boton_imprimir;
    private javax.swing.JButton c_boton_mostrarclientes;
    private javax.swing.JButton c_boton_mostrarproductos;
    private javax.swing.JButton c_boton_mostrarususarios;
    private javax.swing.JButton c_boton_salir;
    private javax.swing.JButton c_botonlimpiar;
    private javax.swing.JComboBox<String> c_combo_ano;
    private javax.swing.JComboBox<String> c_combo_dia;
    private javax.swing.JComboBox<String> c_combo_mes;
    private javax.swing.JTextField c_text_cedula;
    private javax.swing.JTextField c_text_cedulapedido;
    private javax.swing.JTable cn_tablaconsultas;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
