/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

import com.codigo.Cliente;
import com.codigo.Pedido;
import com.codigo.Torta;
import com.codigo.Usuario;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juanfer
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    
    int x,y;
    public Factura() {
        
         this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Factura(Pedido pedido ) {
        
        if(pedido==null)
            return;
            
        LinkedList<Pedido> pedidos = Pedido.getPedidos(pedido);
        
        if (pedidos == null){
            return;
        }
        
        System.out.println(pedido.toString());
        
        LinkedList<Torta> SusTortas = new LinkedList<>();        
        LinkedList<Integer> SusCantidades = new LinkedList<>();
        
        Torta.extraerTortas(pedidos, SusTortas, SusCantidades);
        
        Cliente cliente = Cliente.getCliente((int) pedido.getCedula_cliente());
        Usuario usuario = Usuario.getUsuario((int) pedido.getCedula_usuario());
        
        if(cliente==null||usuario==null || SusTortas == null || SusCantidades==null ){
            
            return;
            
        }
        
        
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        
        f_tidpedido.setText(pedidos.getFirst().getId_numero()+"");
        f_tvendedor.setText(usuario.getNombre() + " " + usuario.getApellido());
        f_tfecha.setText(pedido.getFechaTexto());
        cp_testado.setText(pedido.getEstado());
        
        f_cedulacliente.setText(cliente.getCedula()+"");
        f_nombrecliente.setText(cliente.getNombres()+"");
        
        //Esto es para calcular el subtotal
        
       double subtotal = 0.0;
        
        System.out.println("*********************");
        for (int i = 0; i < SusTortas.size(); i++) {
            System.out.println(SusTortas.get(i).toString());
            System.out.println(SusCantidades.get(i));
            subtotal += SusTortas.get(i).getPrecio() * SusCantidades.get(i);
        }
        
        t_subtotal.setText("$" + subtotal);
        t_total.setText("$" + subtotal);
        
        
        //Llenar Tabla
        
         DefaultTableModel model = (DefaultTableModel) in_tabla.getModel();
         
         for (int i = 0; i < SusTortas.size(); i++) {
             
             Torta t = SusTortas.get(i);
              int j = indiceTorta(t.getCodigo(), SusTortas);
              
               Object[] producto = new Object [5];

               producto [0] = SusCantidades.get(i);
               
                producto [1] = t.getCodigo(); 
                producto [2] = t.getSabor();
                producto [3] = t.getPrecio();
                
                producto[4]=t.getPrecio()*SusCantidades.get(i);
                
                 model.addRow(producto);

               
            
        }

            in_tabla.setModel(model);
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        in_boton_mostrarfactura3 = new javax.swing.JButton();
        ac_boton_salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        f_tvendedor = new javax.swing.JLabel();
        f_tfecha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        in_tabla = new javax.swing.JTable();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        f_tidpedido = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        f_nombrecliente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        f_cedulacliente = new javax.swing.JLabel();
        t_subtotal = new javax.swing.JLabel();
        t_iva = new javax.swing.JLabel();
        t_total = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cp_testado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setText("Tortas Caseras Doña Boli");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Sixta Bolivia Torres");

        in_boton_mostrarfactura3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_mostrarfactura3.setText("Imprimir");
        in_boton_mostrarfactura3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_mostrarfactura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_mostrarfactura3ActionPerformed(evt);
            }
        });

        ac_boton_salir.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ac_boton_salir.setText("Salir");
        ac_boton_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ac_boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac_boton_salirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("Nit: 66.943.132");

        f_tvendedor.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        f_tvendedor.setText("Juan Puche");

        f_tfecha.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        f_tfecha.setText("16/05/2021");

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("Vendedor:");

        in_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Cod.", "Descripcion", "Precio Unit.", "Importe"
            }
        ));
        jScrollPane1.setViewportView(in_tabla);

        jLabel71.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel71.setText("Subtotal:");

        jLabel72.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel72.setText("IVA:");

        jLabel78.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel78.setText("TOTAL:");

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel10.setText("Factura del pedido:");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Separador.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Separador.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("***GRACIAS POR PREFERIRNOS***");

        f_tidpedido.setText("01");

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel13.setText("ID_Cliente:");

        f_nombrecliente.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        f_nombrecliente.setText("Juan David");

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel14.setText("Nombres:");

        f_cedulacliente.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        f_cedulacliente.setText("1007758565");

        t_subtotal.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        t_subtotal.setText("19000");

        t_iva.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        t_iva.setText("0");

        t_total.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        t_total.setText("19000");

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel17.setText("$");

        jLabel16.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel16.setText("Estado: ");

        cp_testado.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        cp_testado.setText("Entregado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel71)
                            .addComponent(jLabel72))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_total)
                            .addComponent(t_iva)
                            .addComponent(t_subtotal))
                        .addGap(54, 54, 54)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel3)))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(in_boton_mostrarfactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(ac_boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_tidpedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cp_testado)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f_cedulacliente)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f_tvendedor)
                                        .addGap(141, 141, 141)
                                        .addComponent(f_tfecha))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(f_nombrecliente))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(277, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(cp_testado))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(f_tidpedido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_tfecha)
                    .addComponent(jLabel9)
                    .addComponent(f_tvendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(f_cedulacliente))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(f_nombrecliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(t_subtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(t_iva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(t_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_boton_mostrarfactura3)
                    .addComponent(ac_boton_salir))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(260, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(321, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
         x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       this.setLocation(this.getLocation().x+evt.getX()-x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void in_boton_mostrarfactura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_mostrarfactura3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_boton_mostrarfactura3ActionPerformed

    private void ac_boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac_boton_salirActionPerformed

        Factura fra=new Factura();
        fra.setVisible(false);
        dispose();

    }//GEN-LAST:event_ac_boton_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ac_boton_salir;
    private javax.swing.JLabel cp_testado;
    private javax.swing.JLabel f_cedulacliente;
    private javax.swing.JLabel f_nombrecliente;
    private javax.swing.JLabel f_tfecha;
    private javax.swing.JLabel f_tidpedido;
    private javax.swing.JLabel f_tvendedor;
    private javax.swing.JButton in_boton_mostrarfactura3;
    private javax.swing.JTable in_tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel t_iva;
    private javax.swing.JLabel t_subtotal;
    private javax.swing.JLabel t_total;
    // End of variables declaration//GEN-END:variables

 private int indiceTorta(String codigo, LinkedList<Torta> SusTortas) {
      
        int res = -1;
        
        int i = 0;
        
        for (Torta t: SusTortas){
            
            if (t.getCodigo()==codigo){
            
            
                
                return i;
            }
            
            i ++;
            
        }
        
        return res;
        
        
    }

}


