/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import  com.codigo.Cliente;
import com.codigo.Pedido;
import com.codigo.Torta;
import java.time.LocalDateTime;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juanfer
 */
public class VistaPrincipal extends javax.swing.JFrame implements Runnable {

   String hora, minutos, segundos, ampm, nombreUsuario;
   int ano, mes, dia, cedulaUsuario;
   Calendar calendario;
   Thread h1;
   LinkedList<Torta> SusTortas;  
   LinkedList<Integer>SusCantidades;
    Pedido pedido;
    
    public VistaPrincipal(int user, String nombre) {
        cedulaUsuario = user;
        nombreUsuario = nombre;
        initComponents();     
        this.setLocationRelativeTo(null);
        setTitle("Sistema y Control de Ventas V 1.01");
        h1=new Thread(this);
        h1.start();
        in_tusuario.setText(cedulaUsuario + "");
        in_tnombrevendedor.setText(nombreUsuario);
    }

    private VistaPrincipal() {
        initComponents();     
        this.setLocationRelativeTo(null);
        setTitle("Sistema y Control de Ventas V 1.01");
        h1=new Thread(this);
        h1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        in_boton_registrarpedido = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        in_tcedulacliente = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel74 = new javax.swing.JLabel();
        in_tusuario = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel20 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        in_tmuestracedula = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        in_tmuestranombre = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        in_tmuestraapellidos = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        in_tmuestradireccion = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        in_tmuestracelular = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel75 = new javax.swing.JLabel();
        in_tnombrevendedor = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel79 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        in_tcodigotorta = new javax.swing.JTextField();
        in_boton_anadir = new javax.swing.JButton();
        in_boton_borrar = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        in_tabla = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        t_subtotal = new javax.swing.JLabel();
        t_iva = new javax.swing.JLabel();
        t_total = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        in_boton_guardarpedido = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        in_tnumeropedido = new javax.swing.JTextField();
        in_boton_consultar = new javax.swing.JButton();
        in_boton_cambiarestadopedido = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel80 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel81 = new javax.swing.JLabel();
        in_boton_salir = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        lbhora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setForeground(new java.awt.Color(252, 162, 95));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        in_boton_registrarpedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_registrarpedido.setText("Generar Pedido");
        in_boton_registrarpedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_registrarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_registrarpedidoActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel57.setText("Cedula Cliente:");

        in_tcedulacliente.setBorder(null);
        in_tcedulacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tcedulaclienteActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(in_tcedulacliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(in_boton_registrarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(in_tcedulacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel57)))
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(in_boton_registrarpedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel74.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel74.setText("Usuario:");

        in_tusuario.setEditable(false);
        in_tusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tusuarioActionPerformed(evt);
            }
        });

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/Logo2.png"))); // NOI18N

        jSeparator17.setForeground(new java.awt.Color(204, 204, 204));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jLabel66.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel66.setText("Cedula Cliente:");

        in_tmuestracedula.setForeground(new java.awt.Color(153, 153, 153));
        in_tmuestracedula.setBorder(null);
        in_tmuestracedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tmuestracedulaActionPerformed(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel67.setText("Nombre:");
        jLabel67.setToolTipText("");

        in_tmuestranombre.setForeground(new java.awt.Color(153, 153, 153));
        in_tmuestranombre.setBorder(null);
        in_tmuestranombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tmuestranombreActionPerformed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel68.setText("Apellidos:");
        jLabel68.setToolTipText("");

        in_tmuestraapellidos.setForeground(new java.awt.Color(153, 153, 153));
        in_tmuestraapellidos.setBorder(null);
        in_tmuestraapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tmuestraapellidosActionPerformed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel69.setText("Direccion:");

        in_tmuestradireccion.setForeground(new java.awt.Color(153, 153, 153));
        in_tmuestradireccion.setBorder(null);
        in_tmuestradireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tmuestradireccionActionPerformed(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel70.setText("Celular:");

        in_tmuestracelular.setForeground(new java.awt.Color(153, 153, 153));
        in_tmuestracelular.setBorder(null);
        in_tmuestracelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tmuestracelularActionPerformed(evt);
            }
        });

        jSeparator14.setForeground(new java.awt.Color(255, 204, 153));

        jSeparator16.setForeground(new java.awt.Color(255, 204, 153));

        jSeparator18.setForeground(new java.awt.Color(255, 204, 153));

        jSeparator19.setForeground(new java.awt.Color(255, 204, 153));

        jSeparator20.setForeground(new java.awt.Color(255, 204, 153));

        jLabel75.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel75.setText("Vendedor:");
        jLabel75.setToolTipText("");

        in_tnombrevendedor.setForeground(new java.awt.Color(153, 153, 153));
        in_tnombrevendedor.setBorder(null);
        in_tnombrevendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tnombrevendedorActionPerformed(evt);
            }
        });

        jSeparator22.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel66)
                    .addComponent(jLabel69)
                    .addComponent(jLabel75))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(in_tmuestracedula, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator20)
                                        .addComponent(in_tmuestradireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel20Layout.createSequentialGroup()
                                        .addComponent(jLabel70)
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(in_tmuestracelular)
                                                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel20Layout.createSequentialGroup()
                                        .addComponent(jLabel67)
                                        .addGap(18, 18, 18)
                                        .addComponent(in_tmuestranombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel68)))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(in_tmuestraapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jSeparator19))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator22, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(in_tnombrevendedor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel75)
                    .addComponent(in_tnombrevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(in_tmuestracedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67)
                    .addComponent(in_tmuestranombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(in_tmuestraapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addComponent(in_tmuestracelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel69))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(in_tmuestradireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel70))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        jLabel79.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel79.setText("Registrar Pedido:");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel63.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel63.setText("Codigo Torta:");

        in_tcodigotorta.setForeground(new java.awt.Color(204, 204, 204));
        in_tcodigotorta.setBorder(null);
        in_tcodigotorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tcodigotortaActionPerformed(evt);
            }
        });

        in_boton_anadir.setBackground(new java.awt.Color(153, 255, 153));
        in_boton_anadir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        in_boton_anadir.setText("+");
        in_boton_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_anadirActionPerformed(evt);
            }
        });

        in_boton_borrar.setBackground(new java.awt.Color(255, 153, 153));
        in_boton_borrar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        in_boton_borrar.setText("-");
        in_boton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_borrarActionPerformed(evt);
            }
        });

        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator21.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_tcodigotorta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(in_boton_anadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_boton_borrar)
                .addContainerGap(371, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel63)
                            .addComponent(in_tcodigotorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(in_boton_anadir)
                        .addComponent(in_boton_borrar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        in_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Cod.", "Descripcion", "Precio Unit.", "Importe"
            }
        ));
        jScrollPane1.setViewportView(in_tabla);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jLabel71.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel71.setText("Subtotal:");

        jLabel72.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel72.setText("IVA:");

        jLabel78.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel78.setText("TOTAL:");

        t_subtotal.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        t_subtotal.setText("0");

        t_iva.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        t_iva.setText("0");

        t_total.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        t_total.setText("0");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(jLabel72)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_iva)
                    .addComponent(t_subtotal)
                    .addComponent(t_total))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(t_subtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(t_iva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(t_total))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        in_boton_guardarpedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_guardarpedido.setText("Guardar Pedido");
        in_boton_guardarpedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_guardarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_guardarpedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(in_boton_guardarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(in_boton_guardarpedido)
                .addGap(34, 34, 34))
        );

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));

        jLabel73.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel73.setText("Numero de Pedido:");

        in_tnumeropedido.setForeground(new java.awt.Color(204, 204, 204));
        in_tnumeropedido.setBorder(null);
        in_tnumeropedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_tnumeropedidoActionPerformed(evt);
            }
        });

        in_boton_consultar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_consultar.setText("Consultar");
        in_boton_consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_consultarActionPerformed(evt);
            }
        });

        in_boton_cambiarestadopedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_cambiarestadopedido.setText("Cambiar Estado");
        in_boton_cambiarestadopedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_cambiarestadopedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_cambiarestadopedidoActionPerformed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(255, 204, 153));

        jLabel80.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel80.setText("Pedido Registrado:");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(in_boton_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(in_boton_cambiarestadopedido))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addComponent(in_tnumeropedido))))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel80)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(in_tnumeropedido, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_boton_consultar)
                    .addComponent(in_boton_cambiarestadopedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));

        jLabel81.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel81.setText("Añadir Productos:");

        in_boton_salir.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_salir.setText("Salir");
        in_boton_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_salirActionPerformed(evt);
            }
        });

        jPanel32.setBackground(new java.awt.Color(255, 204, 153));

        jLabel93.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel93.setText("Fecha:");

        jLabel94.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel94.setText("Hora:");

        lbfecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbfecha.setText("10/05/2021");

        lbhora.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbhora.setText("14:35:04 P.M.");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel93)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbfecha))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbhora)))
                .addContainerGap())
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbfecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel94)
                    .addComponent(lbhora))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel77)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel79)
                                .addGap(19, 19, 19))
                            .addComponent(jPanel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(in_tusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jSeparator17)
                .addGap(127, 127, 127))
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(in_boton_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel81)
                .addGap(20, 20, 20))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel77)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel74)
                            .addComponent(in_tusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel79)
                        .addGap(7, 7, 7)))
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(in_boton_salir)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jMenu12.setText("Cliente");
        jMenu12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono11.png"))); // NOI18N
        jMenuItem2.setText("Añadir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem2);

        jMenuItem1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono 2.png"))); // NOI18N
        jMenuItem1.setText("Actualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem1);

        jMenuItem3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono 3.png"))); // NOI18N
        jMenuItem3.setText("Consultar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem3);

        jMenuBar2.add(jMenu12);

        jMenu13.setText("Usuario");
        jMenu13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/Icono11.png"))); // NOI18N
        jMenuItem4.setText("Añadir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono 2.png"))); // NOI18N
        jMenuItem5.setText("Actualizar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono 3.png"))); // NOI18N
        jMenuItem6.setText("Consultar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem6);

        jMenuBar2.add(jMenu13);

        jMenu14.setText("Productos");
        jMenu14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/Icono11.png"))); // NOI18N
        jMenuItem7.setText("Añadir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono 2.png"))); // NOI18N
        jMenuItem8.setText("Actualizar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono 3.png"))); // NOI18N
        jMenuItem9.setText("Consultar");
        jMenu14.add(jMenuItem9);

        jMenuBar2.add(jMenu14);

        jMenu15.setText("Consultas");
        jMenu15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono 4.png"))); // NOI18N
        jMenuItem10.setText("Consultas Negocio");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem10);

        jMenuBar2.add(jMenu15);

        jMenu1.setText("Acerca de");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono I.png"))); // NOI18N
        jMenuItem11.setText("Informacion");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void in_boton_registrarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_registrarpedidoActionPerformed
        try {
            
            int cedula = Integer.parseInt(in_tcedulacliente.getText());
            
            Cliente cliente = Cliente.getCliente(cedula);
            
            
            if(cliente==null){
                
                JOptionPane.showMessageDialog(null, "El cliente no existe, por favor agreguelo.");
                
                return;

            }
           
            
            int res = JOptionPane.showConfirmDialog(null, "Se generará un pedido al cliente: " + cliente.toString());
            
            if(res == JOptionPane.YES_OPTION)
                
            {
                
                in_tnombrevendedor.setText(nombreUsuario);
                in_tmuestracedula.setText(cedula + "");
                in_tmuestranombre.setText(cliente.getNombres());
                in_tmuestraapellidos.setText(cliente.getApellidos());
                in_tmuestradireccion.setText(cliente.getDireccion());
                in_tmuestracelular.setText(cliente.getCelular()+"");
                
                SusTortas = new LinkedList();
                
            }
            
            
//            pedido = new Pedido(cedula, LocalDate.now(),"No entregado");
            pedido = new Pedido(cliente.getCedula(),cedulaUsuario,LocalDateTime.now(),Pedido.ESTADO_NO_ENTREGADO);
            
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Usted ingreso un valor no numerico en el campo Cedula Cliente. Por favor verifique e intente nuevamente.");
            
        }catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Ocurrio un error"+e.getMessage());

        }
        
        

        
        
        
        
    }//GEN-LAST:event_in_boton_registrarpedidoActionPerformed

    private void in_tcedulaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tcedulaclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tcedulaclienteActionPerformed

    private void in_tusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tusuarioActionPerformed

    private void in_tmuestracedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tmuestracedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tmuestracedulaActionPerformed

    private void in_tmuestranombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tmuestranombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tmuestranombreActionPerformed

    private void in_tmuestraapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tmuestraapellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tmuestraapellidosActionPerformed

    private void in_tmuestradireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tmuestradireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tmuestradireccionActionPerformed

    private void in_tmuestracelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tmuestracelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tmuestracelularActionPerformed

    private void in_tcodigotortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tcodigotortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tcodigotortaActionPerformed

    private void in_boton_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_anadirActionPerformed
        
        if (SusTortas == null)
            SusTortas = new LinkedList<>();
        
        System.out.println("Tortas:");
        
        for (Torta SusTorta : SusTortas) {
            System.out.println(SusTorta.getCodigo());
        }
        
        if (SusCantidades == null)
            SusCantidades = new LinkedList<>();
        
        System.out.println("SusCantidades: ");
        
        for (Integer SusCantidade : SusCantidades) {
            System.out.println(SusCantidade);
        }
        
        
        
        String codigo = in_tcodigotorta.getText();

        if (codigo.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo vacio. Por favor escriba el codigo del producto antes de añadirlo.");
            return;
        }

        //caja negra
        Torta t = Torta.getTorta(codigo);

        if (t == null){
            JOptionPane.showMessageDialog(null, "El producto que desea agregar, no existe.");
        }
        else{

            if(SusTortas==null){

                SusTortas = new LinkedList();

            }


            DefaultTableModel model = (DefaultTableModel) in_tabla.getModel();

            Object[] producto = new Object [5];

                producto [1] = t.getCodigo(); 
                producto [2] = t.getSabor();
                producto [3] = t.getPrecio();

                int i = indiceTorta(codigo);



            if(i<0){


            producto [0] = 1;
            producto [4] = t.getPrecio()* (int) producto[0];


                model.addRow(producto);
                SusTortas.add(t);
                SusCantidades.add(1);

            } else {

               SusCantidades.set(i, 1 + SusCantidades.get(i));
               producto [0] = SusCantidades.get(i);
               producto [4] = t.getPrecio()* (int) producto[0];

               model.setValueAt(producto [0], i, 0);
               model.setValueAt(producto [4], i, 4);


            }


            in_tabla.setModel(model);
            ActualizarSubtotal();

        }

    }//GEN-LAST:event_in_boton_anadirActionPerformed

    private void in_boton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_borrarActionPerformed
       
         String codigo = in_tcodigotorta.getText();

        if (codigo.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo vacio. Por favor escriba el codigo del producto antes de eliminarlo.");
            
            return;
        }

       
        int i = indiceTorta(codigo);
        DefaultTableModel model = (DefaultTableModel) in_tabla.getModel();

            Object[] producto = new Object [5];
        
        if(i < 0){
            
            JOptionPane.showMessageDialog(null, "Falla al eliminar: No se encontro en la lista.");
            
        }else if(SusCantidades.get(i) == 1){
            SusCantidades.remove(i);
            SusTortas.remove(i);
            model.removeRow(i);

        }
        
        else{
            
            Torta t = Torta.getTorta(codigo);
            
            SusCantidades.set(i,(SusCantidades.get(i)-1));
            producto [0] = SusCantidades.get(i);
            producto [4] = t.getPrecio()* (int) producto[0];

               model.setValueAt(producto [0], i, 0);
               model.setValueAt(producto [4], i, 4);

        }
        
        in_tabla.setModel(model);
        
         ActualizarSubtotal();
        
        
        
        
        
        
        
    }//GEN-LAST:event_in_boton_borrarActionPerformed

    private void in_boton_guardarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_guardarpedidoActionPerformed

            boolean res = Pedido.insertarPedido(pedido,SusTortas,SusCantidades);
            
            if (res){
                
                
                JOptionPane.showMessageDialog(null, "El pedido se guardo satisfactoriamente.");
                
                        Factura fra=new Factura(pedido);
                        
                        fra.setVisible(true);
   
            }
            
            else{
                
                JOptionPane.showMessageDialog(null, "El pedido no se guardo.");
                
            }
        
            
            
        
        
        
    }//GEN-LAST:event_in_boton_guardarpedidoActionPerformed

    private void in_tnumeropedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tnumeropedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tnumeropedidoActionPerformed

    private void in_boton_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_consultarActionPerformed
       
         String numero = (in_tnumeropedido.getText());
        
        if(numero.isEmpty()){
            
            JOptionPane.showMessageDialog(null, "El campo del numero de pedido esta vacio.");
            return;
        }
        
        Pedido pedido = Pedido.getPedido(numero);
        
        if(pedido==null){
            
            JOptionPane.showMessageDialog(null, "El pedido no existe.");
            return;          
        }
        
        System.out.println(pedido.toString());
       
        Factura fra=new Factura(pedido);
        fra.setVisible(true);
        
    }//GEN-LAST:event_in_boton_consultarActionPerformed

    private void in_boton_cambiarestadopedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_cambiarestadopedidoActionPerformed
        CambiarEstado fra=new CambiarEstado();
        fra.setVisible(true);
    }//GEN-LAST:event_in_boton_cambiarestadopedidoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        
        AnadirCliente fra=new AnadirCliente();
        fra.setVisible(true);
        
        
      
        
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        ActualizarCliente fra=new ActualizarCliente();
        fra.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         
        ConsultarCliente fra=new ConsultarCliente();
        fra.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        AnadirUsuario fra=new  AnadirUsuario();
        fra.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ActualizarUsuario fra=new ActualizarUsuario();
        fra.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        ConsultarCliente fra=new ConsultarCliente();
        fra.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       
        
        AnadirProducto fra=new  AnadirProducto();
        fra.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       
         ActualizarProducto fra=new ActualizarProducto();
        fra.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
         Informacion fra=new Informacion();
        fra.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        ConsultasNegocio fra=new ConsultasNegocio();
        fra.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void in_tnombrevendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_tnombrevendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_tnombrevendedorActionPerformed

    private void in_boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_salirActionPerformed
       
        System.exit(0);
    }//GEN-LAST:event_in_boton_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton in_boton_anadir;
    private javax.swing.JButton in_boton_borrar;
    private javax.swing.JButton in_boton_cambiarestadopedido;
    private javax.swing.JButton in_boton_consultar;
    private javax.swing.JButton in_boton_guardarpedido;
    private javax.swing.JButton in_boton_registrarpedido;
    private javax.swing.JButton in_boton_salir;
    private javax.swing.JTable in_tabla;
    private javax.swing.JTextField in_tcedulacliente;
    private javax.swing.JTextField in_tcodigotorta;
    private javax.swing.JTextField in_tmuestraapellidos;
    private javax.swing.JTextField in_tmuestracedula;
    private javax.swing.JTextField in_tmuestracelular;
    private javax.swing.JTextField in_tmuestradireccion;
    private javax.swing.JTextField in_tmuestranombre;
    private javax.swing.JTextField in_tnombrevendedor;
    private javax.swing.JTextField in_tnumeropedido;
    private javax.swing.JTextField in_tusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbhora;
    private javax.swing.JLabel t_iva;
    private javax.swing.JLabel t_subtotal;
    private javax.swing.JLabel t_total;
    // End of variables declaration//GEN-END:variables

  
    
     @Override
    public void run() {
        
        Thread ct=Thread.currentThread();
        
        while (ct==h1){
            calcula();
            lbhora.setText(hora+":"+minutos+":"+segundos+" "+ampm);
            //lbfecha.setText(ano+"-"+mes+"-"+dia);
            lbfecha.setText(dia+"/"+mes+"/"+ano);
            try {
                Thread.sleep(1000);
                
            } catch (Exception e) {
            }
        
        
        }
        
        
    }

    private void calcula() {
       
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual=new Date();
        
        calendario.setTime(fechaHoraActual);
        ampm=calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        
        ano=calendario.get(Calendar.YEAR);
        mes=calendario.get(Calendar.MONTH)+1;
        dia=  calendario.get(Calendar.DAY_OF_WEEK)+7;
        
        if(ampm.equals("PM")){
            
            int h= calendario.get(Calendar.HOUR_OF_DAY)-12;
            hora = h>9?""+h:"0"+h;
        }else{
               hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        }
        
                minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
                segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
 
    }

    private int indiceTorta(String codigo) {
      
        int res = -1;
        
        int i = 0;
        
        for (Torta t: SusTortas){
            
            if (t.getCodigo().equals(codigo)){
                return i;
            }
            
            i ++;
            
        }
        
        return res;
        
        
    }

    private void ActualizarSubtotal() {
       
        double subtotal = 0.0;
        
        for (int i = 0; i < SusTortas.size(); i++) {
            subtotal += SusTortas.get(i).getPrecio() * SusCantidades.get(i);
        }
        
        t_subtotal.setText("$" + subtotal);
        t_total.setText("$" + subtotal);
    }
}
