/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

/**
 *
 * @author Juanfer
 */
public class VistaCajero extends javax.swing.JFrame {

    /**
     * Creates new form VistaCajero
     */
    public VistaCajero() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Sistema y Control de Ventas V 1.01");
    }

    VistaCajero(int user) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    VistaCajero(int user, String nombre) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        in_boton_registrarpedido1 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        in_text_cedulacliente3 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel74 = new javax.swing.JLabel();
        in_text_cedulacliente5 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel20 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        in_text_numeropedidoAgg4 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        in_text_numeropedidoAgg5 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        in_text_numeropedidoAgg6 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        in_text_numeropedidoAgg7 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        in_text_numeropedidoAgg8 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        in_text_numeropedidoAgg9 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel79 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        in_text_codigotortaAgg1 = new javax.swing.JTextField();
        in_boton_anadiralpedido2 = new javax.swing.JButton();
        in_boton_anadiralpedido3 = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_inicio = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        in_boton_mostrarfactura12 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        in_text_cedulacliente4 = new javax.swing.JTextField();
        in_boton_marcarentrega1 = new javax.swing.JButton();
        in_boton_cancelarpedido1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel80 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel81 = new javax.swing.JLabel();
        in_boton_salir1 = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        lbhora = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setForeground(new java.awt.Color(252, 162, 95));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        in_boton_registrarpedido1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_registrarpedido1.setText("Registrar Pedido");
        in_boton_registrarpedido1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_registrarpedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_registrarpedido1ActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel57.setText("Cedula Cliente:");

        in_text_cedulacliente3.setBorder(null);
        in_text_cedulacliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_cedulacliente3ActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(in_text_cedulacliente3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(in_boton_registrarpedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(in_text_cedulacliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel57)))
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(in_boton_registrarpedido1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel74.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel74.setText("Usuario:");

        in_text_cedulacliente5.setEditable(false);
        in_text_cedulacliente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_cedulacliente5ActionPerformed(evt);
            }
        });

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/Logo2.png"))); // NOI18N

        jSeparator17.setForeground(new java.awt.Color(204, 204, 204));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jLabel65.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel65.setText("Numero Pedido:");

        in_text_numeropedidoAgg4.setForeground(new java.awt.Color(153, 153, 153));
        in_text_numeropedidoAgg4.setBorder(null);
        in_text_numeropedidoAgg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_numeropedidoAgg4ActionPerformed(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel66.setText("Cedula Cliente:");

        in_text_numeropedidoAgg5.setForeground(new java.awt.Color(153, 153, 153));
        in_text_numeropedidoAgg5.setBorder(null);
        in_text_numeropedidoAgg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_numeropedidoAgg5ActionPerformed(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel67.setText("Nombre:");
        jLabel67.setToolTipText("");

        in_text_numeropedidoAgg6.setForeground(new java.awt.Color(153, 153, 153));
        in_text_numeropedidoAgg6.setBorder(null);
        in_text_numeropedidoAgg6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_numeropedidoAgg6ActionPerformed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel68.setText("Apellido:");
        jLabel68.setToolTipText("");

        in_text_numeropedidoAgg7.setForeground(new java.awt.Color(153, 153, 153));
        in_text_numeropedidoAgg7.setBorder(null);
        in_text_numeropedidoAgg7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_numeropedidoAgg7ActionPerformed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel69.setText("Direccion:");

        in_text_numeropedidoAgg8.setForeground(new java.awt.Color(153, 153, 153));
        in_text_numeropedidoAgg8.setBorder(null);
        in_text_numeropedidoAgg8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_numeropedidoAgg8ActionPerformed(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel70.setText("Celular:");

        in_text_numeropedidoAgg9.setForeground(new java.awt.Color(153, 153, 153));
        in_text_numeropedidoAgg9.setBorder(null);
        in_text_numeropedidoAgg9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_numeropedidoAgg9ActionPerformed(evt);
            }
        });

        jSeparator13.setForeground(new java.awt.Color(255, 204, 153));

        jSeparator14.setForeground(new java.awt.Color(255, 204, 153));

        jSeparator16.setForeground(new java.awt.Color(255, 204, 153));

        jSeparator18.setForeground(new java.awt.Color(255, 204, 153));

        jSeparator19.setForeground(new java.awt.Color(255, 204, 153));

        jSeparator20.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(in_text_numeropedidoAgg4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66)
                            .addComponent(jLabel69))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator20)
                                    .addComponent(in_text_numeropedidoAgg8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jLabel70)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator16)
                                    .addComponent(in_text_numeropedidoAgg9, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(jSeparator18)))
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addComponent(jSeparator13, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addGap(400, 400, 400))
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel20Layout.createSequentialGroup()
                                            .addComponent(in_text_numeropedidoAgg5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel67)
                                            .addGap(10, 10, 10)
                                            .addComponent(in_text_numeropedidoAgg6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(42, 42, 42)
                                            .addComponent(jLabel68))
                                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(in_text_numeropedidoAgg7, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(jSeparator19)))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(in_text_numeropedidoAgg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(in_text_numeropedidoAgg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67)
                    .addComponent(in_text_numeropedidoAgg6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(in_text_numeropedidoAgg7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel69)
                                    .addComponent(jLabel70)
                                    .addComponent(in_text_numeropedidoAgg9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(in_text_numeropedidoAgg8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        jLabel79.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel79.setText("Registrar Pedido:");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel63.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel63.setText("Codigo Torta:");

        in_text_codigotortaAgg1.setForeground(new java.awt.Color(204, 204, 204));
        in_text_codigotortaAgg1.setText("Digite el codigo");
        in_text_codigotortaAgg1.setBorder(null);
        in_text_codigotortaAgg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_codigotortaAgg1ActionPerformed(evt);
            }
        });

        in_boton_anadiralpedido2.setBackground(new java.awt.Color(153, 255, 153));
        in_boton_anadiralpedido2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        in_boton_anadiralpedido2.setText("+");
        in_boton_anadiralpedido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_anadiralpedido2ActionPerformed(evt);
            }
        });

        in_boton_anadiralpedido3.setBackground(new java.awt.Color(255, 153, 153));
        in_boton_anadiralpedido3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        in_boton_anadiralpedido3.setText("-");
        in_boton_anadiralpedido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_anadiralpedido3ActionPerformed(evt);
            }
        });

        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator21.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_text_codigotortaAgg1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(in_boton_anadiralpedido2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_boton_anadiralpedido3)
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel63)
                            .addComponent(in_text_codigotortaAgg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(in_boton_anadiralpedido2)
                        .addComponent(in_boton_anadiralpedido3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabla_inicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Cod.", "Descripcion", "Precio Unit.", "Importe"
            }
        ));
        jScrollPane1.setViewportView(tabla_inicio);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jLabel71.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel71.setText("Subtotal:");

        jLabel72.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel72.setText("IVA:");

        jLabel78.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel78.setText("TOTAL:");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(jLabel72)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel78)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        in_boton_mostrarfactura12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_mostrarfactura12.setText("Guardar Pedido");
        in_boton_mostrarfactura12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_mostrarfactura12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_mostrarfactura12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(in_boton_mostrarfactura12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(in_boton_mostrarfactura12)
                .addGap(34, 34, 34))
        );

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));

        jLabel73.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel73.setText("Numero de Pedido:");

        in_text_cedulacliente4.setForeground(new java.awt.Color(204, 204, 204));
        in_text_cedulacliente4.setBorder(null);
        in_text_cedulacliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_text_cedulacliente4ActionPerformed(evt);
            }
        });

        in_boton_marcarentrega1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_marcarentrega1.setText("Consultar");
        in_boton_marcarentrega1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_marcarentrega1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_marcarentrega1ActionPerformed(evt);
            }
        });

        in_boton_cancelarpedido1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_cancelarpedido1.setText("Cambiar Estado");
        in_boton_cancelarpedido1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_boton_cancelarpedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_boton_cancelarpedido1ActionPerformed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(255, 204, 153));

        jLabel80.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel80.setText("Pedido Registrado:");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(in_boton_marcarentrega1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(in_boton_cancelarpedido1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addComponent(in_text_cedulacliente4))))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel80)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(in_text_cedulacliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_boton_marcarentrega1)
                    .addComponent(in_boton_cancelarpedido1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));

        jLabel81.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel81.setText("Añadir Productos:");

        in_boton_salir1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        in_boton_salir1.setText("Salir");
        in_boton_salir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel32.setBackground(new java.awt.Color(255, 204, 153));

        jLabel93.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel93.setText("Fecha:");

        jLabel94.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel94.setText("Hora:");

        lbfecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbfecha.setText("10/05/2021");

        lbhora.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbhora.setText("14:35:04 P.M.");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel93)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbfecha))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbhora)))
                .addContainerGap())
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbfecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel94)
                    .addComponent(lbhora))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel79)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(in_text_cedulacliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jSeparator17)
                .addGap(127, 127, 127))
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(in_boton_salir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel81)
                .addGap(20, 20, 20))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel77)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel74)
                            .addComponent(in_text_cedulacliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel79)
                        .addGap(7, 7, 7)))
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(in_boton_salir1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jMenu12.setText("Cliente");
        jMenu12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono11.png"))); // NOI18N
        jMenuItem2.setText("Añadir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem2);

        jMenuItem1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono 2.png"))); // NOI18N
        jMenuItem1.setText("Actualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem1);

        jMenuItem3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono 3.png"))); // NOI18N
        jMenuItem3.setText("Consultar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem3);

        jMenuBar2.add(jMenu12);

        jMenu1.setText("Acerca de");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Icono I.png"))); // NOI18N
        jMenuItem11.setText("Informacion");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void in_boton_registrarpedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_registrarpedido1ActionPerformed

        //        //Simulador
        //
        //        String numeropedido="A01";
        //        String cedula = in_text_cedulacliente3.getText();
        //        String nombre= "JUAN";
        //        String apellido="PUCHE";
        //        String dir="Cra 96 ·48-38";
        //
        //        int res=JOptionPane.showConfirmDialog(null, "A continuacion se creara un pedido al cliente: C.C 1234 JUAN PUCHE");
        //
        //        if(res == JOptionPane.YES_OPTION){
            //
            //            in_text_numeropedidoAgg4.setText(numeropedido);
            //            in_text_numeropedidoAgg5.setText(cedula);
            //            in_text_numeropedidoAgg6.setText(nombre);
            //            in_text_numeropedidoAgg7.setText(apellido);
            //            in_text_numeropedidoAgg8.setText(dir);
            //
            //        }
        //
        //        else {
            //
            //            in_text_cedulacliente3.setText(null);
            //        }
    }//GEN-LAST:event_in_boton_registrarpedido1ActionPerformed

    private void in_text_cedulacliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_cedulacliente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_cedulacliente3ActionPerformed

    private void in_text_cedulacliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_cedulacliente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_cedulacliente5ActionPerformed

    private void in_text_numeropedidoAgg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_numeropedidoAgg4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_numeropedidoAgg4ActionPerformed

    private void in_text_numeropedidoAgg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_numeropedidoAgg5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_numeropedidoAgg5ActionPerformed

    private void in_text_numeropedidoAgg6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_numeropedidoAgg6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_numeropedidoAgg6ActionPerformed

    private void in_text_numeropedidoAgg7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_numeropedidoAgg7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_numeropedidoAgg7ActionPerformed

    private void in_text_numeropedidoAgg8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_numeropedidoAgg8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_numeropedidoAgg8ActionPerformed

    private void in_text_numeropedidoAgg9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_numeropedidoAgg9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_numeropedidoAgg9ActionPerformed

    private void in_text_codigotortaAgg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_codigotortaAgg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_codigotortaAgg1ActionPerformed

    private void in_boton_anadiralpedido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_anadiralpedido2ActionPerformed
        //        String codigo = in_text_codigotortaAgg1.getText();
        //
        //        if (codigo.isEmpty()){
            //            JOptionPane.showMessageDialog(null, "Campo vacio. Por favor escriba el codigo del producto antes de enviar.");
            //        }
        //
        //        else {
            //
            //            //caja negra
            //            Torta t = Torta.getTorta(codigo);
            //
            //            if (t == null){
                //                JOptionPane.showMessageDialog(null, "El producto que desea agregar, no existe.");
                //            }
            //            else{
                //
                //            }
            //        }
    }//GEN-LAST:event_in_boton_anadiralpedido2ActionPerformed

    private void in_boton_anadiralpedido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_anadiralpedido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_boton_anadiralpedido3ActionPerformed

    private void in_boton_mostrarfactura12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_mostrarfactura12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_boton_mostrarfactura12ActionPerformed

    private void in_text_cedulacliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_text_cedulacliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_text_cedulacliente4ActionPerformed

    private void in_boton_marcarentrega1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_marcarentrega1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_boton_marcarentrega1ActionPerformed

    private void in_boton_cancelarpedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_boton_cancelarpedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_boton_cancelarpedido1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        AnadirCliente fra=new AnadirCliente();
        fra.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        ActualizarCliente fra=new ActualizarCliente();
        fra.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        ConsultarCliente fra=new ConsultarCliente();
        fra.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Informacion fra=new Informacion();
        fra.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton in_boton_anadiralpedido2;
    private javax.swing.JButton in_boton_anadiralpedido3;
    private javax.swing.JButton in_boton_cancelarpedido1;
    private javax.swing.JButton in_boton_marcarentrega1;
    private javax.swing.JButton in_boton_mostrarfactura12;
    private javax.swing.JButton in_boton_registrarpedido1;
    private javax.swing.JButton in_boton_salir1;
    private javax.swing.JTextField in_text_cedulacliente3;
    private javax.swing.JTextField in_text_cedulacliente4;
    private javax.swing.JTextField in_text_cedulacliente5;
    private javax.swing.JTextField in_text_codigotortaAgg1;
    private javax.swing.JTextField in_text_numeropedidoAgg4;
    private javax.swing.JTextField in_text_numeropedidoAgg5;
    private javax.swing.JTextField in_text_numeropedidoAgg6;
    private javax.swing.JTextField in_text_numeropedidoAgg7;
    private javax.swing.JTextField in_text_numeropedidoAgg8;
    private javax.swing.JTextField in_text_numeropedidoAgg9;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbhora;
    private javax.swing.JTable tabla_inicio;
    // End of variables declaration//GEN-END:variables
}
